environment:
  matrix:
#    - nodejs_version: "4"
#    - nodejs_version: "5"
#    - nodejs_version: "6"
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test

build: off